<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Owner-PC" name="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest" tests="20" failures="0" timestamp="13 May 2016 13:37:14 GMT" time="16.283" errors="18">
  <testcase name="selectInstitution" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- selectInstitution -->
  <testcase name="goToHomepage" time="8.814" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest"/>
  <testcase name="checkOrderStatus" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.checkOrderStatus()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkOrderStatus()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkOrderStatus -->
  <testcase name="goToCourseEditPage" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.goToCourseEditPage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.goToCourseEditPage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- goToCourseEditPage -->
  <testcase name="studentLogin" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- studentLogin -->
  <testcase name="viewCart" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.viewCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.viewCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- viewCart -->
  <testcase name="getCourseList" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.getCourseList()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.getCourseList()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- getCourseList -->
  <testcase name="enterStudentLoginDetails" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterStudentLoginDetails -->
  <testcase name="checkout" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.checkout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkout -->
  <testcase name="enterInstitutionLoginDetails" time="0.004" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Unipupil.TestFramework.pageObjects.LoginPage.enterUsername(LoginPage.java:50)
	at Unipupil.TestFramework.pageObjects.LoginPage.unipupilLogin(LoginPage.java:77)
	at Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.enterInstitutionLoginDetails(BuyCourseAdditionalFeesFirefoxTest.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterInstitutionLoginDetails -->
  <testcase name="reviewOrder" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.reviewOrder()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.reviewOrder()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- reviewOrder -->
  <testcase name="addCourseToCart" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- addCourseToCart -->
  <testcase name="selectCourse" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- selectCourse -->
  <testcase name="findInstitution" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- findInstitution -->
  <testcase name="payForProduct" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.payForProduct()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.payForProduct()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- payForProduct -->
  <testcase name="getCourseFees" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.getCourseFees()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.getCourseFees()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- getCourseFees -->
  <testcase name="checkStudentAccount" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.checkStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkStudentAccount -->
  <testcase name="logOut" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.logOut()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.logOut()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- logOut -->
  <testcase name="institutionLogin" time="7.465" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest"/>
  <testcase name="institutionLogout" time="0.000" classname="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
    <error type="java.lang.Throwable" message="Method BuyCourseAdditionalFeesFirefoxTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- institutionLogout -->
</testsuite> <!-- Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest -->
